//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rgat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rgat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] APIDataWin {
            get {
                object obj = ResourceManager.GetObject("APIDataWin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///  &quot;CustomColours&quot;: {
        ///    &quot;PreviewText&quot;: 4294967295,
        ///    &quot;PreviewTextBackground&quot;: 1275068416,
        ///    &quot;PreviewPaneBorder&quot;: 4278190335,
        ///    &quot;PreviewPaneBackground&quot;: 4278979596,
        ///    &quot;PreviewZoomEnvelope&quot;: 2998055602,
        ///    &quot;Heat0Lowest&quot;: 2993500722,
        ///    &quot;Heat1&quot;: 4284890151,
        ///    &quot;Heat2&quot;: 4286269967,
        ///    &quot;Heat3&quot;: 4290797890,
        ///    &quot;Heat4&quot;: 4288161130,
        ///    &quot;Heat5&quot;: 4290528431,
        ///    &quot;Heat6&quot;: 4278543033,
        ///    &quot;Heat7&quot;: 4278217208,
        ///    &quot;Heat8&quot;: 4278190335,
        ///    &quot;Heat9Highest&quot;: 4294901503,
        ///    &quot;VisBarPlotLine [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuiltinJSONThemes {
            get {
                return ResourceManager.GetString("BuiltinJSONThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Field&quot;:&quot;Metadata&quot;},{&quot;Field&quot;:&quot;ProcessRecord&quot;,&quot;BitWidth&quot;:32},{&quot;Field&quot;:&quot;Modules&quot;},[&quot;&quot;,&quot;&quot;],[0,1,2,3],[0,1],{&quot;Field&quot;:&quot;Symbols&quot;,&quot;ModuleCount&quot;:0,&quot;TotalSymbols&quot;:0},{&quot;Field&quot;:&quot;Disassembly&quot;,&quot;Count&quot;:5},[10,0,0,1,&quot;UA==&quot;,1,29628,1],[20,0,0,1,&quot;6D4AAAA=&quot;,1,29628,2],[30,0,1,1,&quot;/yUIIGQA&quot;,1,29628,3],[40,0,1,1,&quot;D4T8////&quot;,1,29628,4],[50,0,1,1,&quot;ww==&quot;,1,29628,5],{&quot;Field&quot;:&quot;BasicBlocks&quot;,&quot;Count&quot;:0},{&quot;Field&quot;:&quot;Externs&quot;,&quot;Count&quot;:0},{&quot;Field&quot;:&quot;Threads&quot;,&quot;Count&quot;:1},{&quot;Field&quot;:&quot;Thread&quot;,&quot;ThreadID&quot;:29628,&quot;StartAddress&quot;:0,&quot;TotalInstructions&quot;:0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompanionTrace {
            get {
                return ResourceManager.GetString("CompanionTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DllLoader32 {
            get {
                object obj = ResourceManager.GetObject("DllLoader32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DllLoader64 {
            get {
                object obj = ResourceManager.GetObject("DllLoader64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Font_Awesome_5_Free_Regular_400 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_5_Free_Regular_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Font_Awesome_5_Free_Solid_900 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_5_Free_Solid_900", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NotoSansSC_Regular {
            get {
                object obj = ResourceManager.GetObject("NotoSansSC_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PinTool32 {
            get {
                object obj = ResourceManager.GetObject("PinTool32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PinTool64 {
            get {
                object obj = ResourceManager.GetObject("PinTool64", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
