//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rgat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rgat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///  &quot;CustomColours&quot;: {
        ///    &quot;ePreviewText&quot;: 4294967295,
        ///    &quot;ePreviewTextBackground&quot;: 1275068416,
        ///    &quot;ePreviewPaneBorder&quot;: 4278190335,
        ///    &quot;ePreviewPaneBackground&quot;: 4278979596,
        ///    &quot;ePreviewZoomEnvelope&quot;: 2998055602,
        ///    &quot;eHeat0Lowest&quot;: 2996502528,
        ///    &quot;eHeat1&quot;: 4288355374,
        ///    &quot;eHeat2&quot;: 4293027935,
        ///    &quot;eHeat3&quot;: 4292841333,
        ///    &quot;eHeat4&quot;: 8703,
        ///    &quot;eHeat5&quot;: 4290036988,
        ///    &quot;eHeat6&quot;: 4288190706,
        ///    &quot;eHeat7&quot;: 4285230073,
        ///    &quot;eHeat8&quot;: 4282401023,
        ///    &quot;eHeat9Highest&quot;: 4278190335,
        ///    &quot;eVisB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuiltinJSONThemes {
            get {
                return ResourceManager.GetString("BuiltinJSONThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DllLoader32 {
            get {
                object obj = ResourceManager.GetObject("DllLoader32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DllLoader64 {
            get {
                object obj = ResourceManager.GetObject("DllLoader64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Font_Awesome_5_Free_Regular_400 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_5_Free_Regular_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Font_Awesome_5_Free_Solid_900 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_5_Free_Solid_900", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NotoSansSC_Regular {
            get {
                object obj = ResourceManager.GetObject("NotoSansSC_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
